### ISSUE TITLE
Relion 5?

### ISSUE THREAD

**Issue by andreanans** [cryoEM-CNIO/CNIO_Relion_Tools#2]
Does anyone know if this works with Relion 5.0 projects?

**Comment by rfleiro** [comment]
Hi, this should work with Relion 5.0 projects. We will add this info to the readme.

Let us know if you find any issues

**Comment by nayimgr** [comment]
@andreanans there were issues with relion_live.py compatibility, they should now be solved, let us know if it works on your end.

**Comment by andreanans** [comment]
I'm trying to view the Relion 5.0 tutorial project with relion_live.py or relion_analyse.py and it's not displaying any of the plots. The following error was noted: "Key Error: rlnCTFIceRingDensity"

**Comment by nayimgr** [comment]
Hey @andreanans 

Am I right to asume you're looking at the pre-calculated results, rather than processing the tutorial movies yourself? If not, please share the ~70 first lines of your `micrographs_ctf.star` file so we can debug.

If that's the case, the CTFFIND job output (`micrographs_ctf.star`) might lack the `rlnCTFIceRingDensity` as I think those data were not actually processed in Relion5-stable, but rather an earlier version. If you use it within a Relion project that has been processed from the beginning with the latest relion version, that shouldn't happen (e.g., you run the tutorial yourself).

We might be able to add back-compatibility if that solves problems with actual data that are now being processed in Relion5 but were started as Relion4 projects.

Let us know.

**Comment by andreanans** [comment]
Correct, I was just trying to display pre-calculated results. I'll run everything in Relion 5.0 stable from scratch and will let you know how it goes.

**Comment by andreanans** [comment]
Unfortunately, the plots are still not displaying. I've started processing from scratch in relion 5.0 stable and the motion data from my motion-correction isn't loading. 

<img width="1911" height="1189" alt="Image" src="https://github.com/user-attachments/assets/012b85d4-169c-49e2-bc83-5a3e960b86ed" />

**Comment by nayimgr** [comment]
hi @andreanans  

well, that's strange... The import job is getting recognized, as the number of movies imported (5770) shows up.

Given that I can't reproduce your bug, could you share the first few lines of the MotionCorr/job002/corrected_micrographs.star file? A couple lines of micrograph data  (i.e., after the second list of column names) should be enough.

Also share the CtfFind/job003/micrographs_ctf.star, same amount of lines, just in case there's another issue with that.

**Comment by andreanans** [comment]
Yes, it looks like it's recognising all of the jobs. I can even change the filter settings and it updates the micrograph selection. Perhaps it's having trouble displaying the plots? I'm using Firefox on a linux machine. Does it require certain widgets to be active for the plots to work?

# version 50001

data_optics

loop_ 
_rlnOpticsGroupName #1 
_rlnOpticsGroup #2 
_rlnMicrographOriginalPixelSize #3 
_rlnVoltage #4 
_rlnSphericalAberration #5 
_rlnAmplitudeContrast #6 
_rlnMicrographPixelSize #7 
opticsGroup1            1     1.610000   200.000000     2.700000     0.100000     1.610000 
 

# version 50001

data_micrographs

loop_ 
_rlnCtfPowerSpectrum #1 
_rlnMicrographName #2 
_rlnMicrographMetadata #3 
_rlnOpticsGroup #4 
_rlnAccumMotionTotal #5 
_rlnAccumMotionEarly #6 
_rlnAccumMotionLate #7 
MotionCorr/job002/Movies/FoilHole_1008300_Data_1007387_0_20251201_152627_Fractions_PS.mrc MotionCorr/job002/Movies/FoilHole_1008300_Data_1007387_0_20251201_152627_Fractions.mrc MotionCo
rr/job002/Movies/FoilHole_1008300_Data_1007387_0_20251201_152627_Fractions.star            1     3.033864     1.153333     1.880532 
MotionCorr/job002/Movies/FoilHole_1008301_Data_1007387_1_20251201_152633_Fractions_PS.mrc MotionCorr/job002/Movies/FoilHole_1008301_Data_1007387_1_20251201_152633_Fractions.mrc MotionCo
rr/job002/Movies/FoilHole_1008301_Data_1007387_1_20251201_152633_Fractions.star


# version 50001

data_optics

loop_ 
_rlnOpticsGroupName #1 
_rlnOpticsGroup #2 
_rlnMicrographOriginalPixelSize #3 
_rlnVoltage #4 
_rlnSphericalAberration #5 
_rlnAmplitudeContrast #6 
_rlnMicrographPixelSize #7 
opticsGroup1            1     1.610000   200.000000     2.700000     0.100000     1.610000 
 

# version 50001

data_micrographs

loop_ 
_rlnMicrographName #1 
_rlnOpticsGroup #2 
_rlnCtfImage #3 
_rlnDefocusU #4 
_rlnDefocusV #5 
_rlnCtfAstigmatism #6 
_rlnDefocusAngle #7 
_rlnCtfFigureOfMerit #8 
_rlnCtfMaxResolution #9 
_rlnCtfIceRingDensity #10 
MotionCorr/job002/Movies/FoilHole_1008300_Data_1007387_0_20251201_152627_Fractions.mrc            1 CtfFind/job003/Movies/FoilHole_1008300_Data_1007387_0_20251201_152627_Fractions_PS.ct
f:mrc 31040.501953 30893.693359   146.808594    -71.02574     0.102875     7.926154     0.552210 
MotionCorr/job002/Movies/FoilHole_1008301_Data_1007387_1_20251201_152633_Fractions.mrc            1 CtfFind/job003/Movies/FoilHole_1008301_Data_1007387_1_20251201_152633_Fractions_PS.ct
f:mrc 28810.128906 28732.433594    77.695312    -21.53905     0.067699     7.562569 

<img width="2132" height="1150" alt="Image" src="https://github.com/user-attachments/assets/e6cdece4-f2a3-4835-8c21-b9f660e8d2cf" />
